language: perl
sudo: true

addons:
  apt:
    packages:
    - r-base 
    - r-base-dev

perl:
  - "5.14"

install:
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb
  - wget https://cran.r-project.org/src/base/R-3/R-3.4.0.tar.gz 
  - tar -xvf R-3.4.0.tar.gz
  - pushd R-3.4.0 && ./configure --with-readline=no --with-x --with-cairo --prefix=/usr && make && sudo make install && popd
  - sudo Rscript -e "install.packages(c('DT', 'ggplot2', 'ggpubr', 'ggrepel', 'markdown', 'Matrix', 'reshape', 'rmarkdown', 'scales', 'XML'), repos='http://mirrors.ebi.ac.uk/CRAN/')"
  - sudo Rscript -e "source('http://bioconductor.org/biocLite.R')" -e "biocLite(c('GenomicRanges', 'graph', 'limma', 'SummarizedExperiment', 'S4Vectors'))"
  - sudo Rscript -e "source('http://bioconductor.org/biocLite.R')" -e "biocLite(c('DESeq2', 'topGO'))"
  - git clone --branch v1.1.1 https://github.com/sanger-pathogens/deago.git
  - pushd deago && git archive --format=tar.gz --prefix=deago-1.1.1/ v1.1.1 >deago-1.1.1.tar.gz && popd
  - pushd deago && sudo Rscript -e "install.packages('deago-1.1.0.tar.gz', repos = NULL, type='source')" && popd

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - "dzil authordeps --missing | cpanm --notest"
  - "dzil listdeps --missing | cpanm --notest"
  - "dzil test" 
